Repository spinnaker/keel, pull requests merged in 2019-11, with the labels that each got.

#573 fix(export): type should be case-insensitive
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExportController.kt
Labels: ready to merge

#572 feat(resource-status): Return PAUSED status for vetoed resources
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
  keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
  keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceId.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceStatusTests.kt
  keel-veto/src/main/kotlin/com/netflix/spinnaker/keel/veto/application/ApplicationVeto.kt
Labels: ready to merge

#584 feat(deb): scheduled fetch latest artifact
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
  keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
  keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ArtifactEvent.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
Labels: auto merged, ready to merge

#586 feat(environments): allowed-times constraint
  keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
  keel-core/keel-core.gradle.kts
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Constraint.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ConstraintEvaluator.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluator.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/InvalidConstraintException.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluatorTests.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluatorTests.kt
Labels: ready to merge

#592 fix(notifications): allow inside voice case
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/NotificationConfig.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/serialization/ArtifactTypeSerializationTests.kt
Labels: ready to merge

#594 feat(environments): db schema for stateful constraints
  keel-sql/src/main/resources/db/changelog/20191108-environment-artifact-constraint.yml
  keel-sql/src/main/resources/db/databaseChangeLog.yml
Labels: ready to merge

#597 fix(actuation): correctly detect active actuations for multi-region resources
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
  keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/CheckSchedulerTests.kt
  keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryPeriodicallyCheckedTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
  keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
Labels: auto merged, ready to merge

#599 fix(diff): do coroutines right
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/AdHocDiffer.kt
  keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/diff/AdHocDifferTests.kt
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
Labels: auto merged, ready to merge

#601 fix(bake): correctly compare package name
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
  keel-clouddriver/src/test/resources/named-images.json
Labels: ready to merge

#602 chore(tests): convert image service test to junit5
  keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
Labels: auto merged, ready to merge

#593 fix(export): Omit fields with default values in cluster spec
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Locatable.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Health.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/LaunchConfiguration.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolverTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
Labels: API, export, ready to merge

#612 update Kotlin & Spinnaker Gradle plugin
  build.gradle.kts
  gradle.properties
Labels: ready to merge

#615 fix(resolution): Gracefully handle missing appversion tag
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/LaunchConfiguration.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
Labels: ready to merge
