Repository spinnaker/keel, pull requests merged in 2020-04, with the labels that each got.

#956 chore(mj): add a timeout test
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/ManualJudgementConstraintEvaluatorTests.kt
Labels: ready to merge

#957 If we can't parse a resource in the database, stop checking
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/CheckSchedulerTests.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepositoryTests.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
  keel-sql/src/main/resources/db/changelog/20200401-resource-check-veto.yml
  keel-sql/src/main/resources/db/databaseChangeLog.yml
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/DummyResourceTypeIdentifier.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
Labels: ready to merge

#960 fix(metrics): Feels like this event should actually go somewhere
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
Labels: ready to merge

#946 feat(tests): Add code coverage report
  README.md
  build.gradle.kts
Labels: code-quality, tests

#966 Clear ignore flag when a resource is updated
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
Labels: ready to merge

#955 feat(security): API permission checks
  docs/authorization.md
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/NoSuchEntityException.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/util.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EnvironmentController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EventController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/InteractiveNotificationCallbackController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/VetoController.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupportTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationTestSupport.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt
Labels: API, ready to merge, security

#981 fix(summary): add artifact reference
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ResourceSummary.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/ApplicationServiceTests.kt
Labels: ready to merge

#976 fix(metrics): record drift from last resource check
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ScheduledResourceCheckStarting.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
Labels: ready to merge

#983 fix(api): Fix authorization for POST /delivery-configs
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationTestSupport.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt
Labels: ready to merge

#982 fix(artifacts): don't keep marking as deployed over and over
  keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactDeployedListener.kt
  keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactDeployedListenerTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
Labels: ready to merge

#974 Schema upgrade
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/Resolver.kt
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/SupportedKind.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DummyResourceSpecIdentifier.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/resources/ResourceSpecIdentifier.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/resources/ResourceTypeIdentifier.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/resources/SpecMigrator.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryCombinedRepositoryTests.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepositoryTests.kt
  keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/SampleDockerImageResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/ec2.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ApplicationLoadBalancerDefaultsResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ClassicLoadBalancerSecurityGroupsResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/KeyPairResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolver.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/DummyResourceTypeIdentifier.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/LegacySpecUpgradeTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlApplicationSummaryGenerationTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepositoryTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlCombinedRepositoryTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryPeriodicallyCheckedTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/config/TitusConfig.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusImageResolver.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/titus.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/KindController.kt
Labels: ready to merge

#988 Compare base AMI versions properly
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
Labels: ready to merge

#990 fix(bake): locate baseami
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
Labels: ready to merge

#993 fix(bake): nice string rather than a garbage string
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
Labels: ready to merge

#991 Make BaseImageCache map to base_ami_version rather than just imageName
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/BaseImageCache.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCacheTests.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
Labels: ready to merge

#996 feat(security): Add Spinnaker authorization headers to downstream calls
  keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
  keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
  keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/EchoService.kt
  keel-front50/keel-front50.gradle.kts
  keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50Service.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluator.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluator.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskLauncher.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgent.kt
  keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluatorTests.kt
  keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluatorTests.kt
  keel-retrofit/keel-retrofit.gradle.kts
  keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/AuthorizationHeadersInterceptor.kt
  keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/KeelRetrofitConfiguration.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt
Labels: ready to merge

#1000 fix(api): Better 403 error messages
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt
Labels: ready to merge

#997 Don't keep re-trying the same bake
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/config/BakeryConfiguration.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/telemetry/BakeryTelemetryListener.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DiffFingerprintRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DiffFingerprintRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDiffFingerprintRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDiffFingerprintRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
  keel-sql/src/main/resources/db/changelog/20200410-rename-diff-fingerprint-column.yml
  keel-sql/src/main/resources/db/databaseChangeLog.yml
Labels: ready to merge

#1008 Don't rebake when we find a region-only diff
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
Labels: ready to merge

#1010 fix(deps): roll back okhttp and kork
  build.gradle.kts
  gradle.properties
Labels: ready to merge

#1011 feat(baking): endpoint to list base AMIs
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/BaseImageCache.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/BaseAmiController.kt
Labels: ready to merge

#1017 fix(core): Ensure there's only ever 1 of each type of configured ObjectMapper
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
Labels: ready to merge

#1023 fix(init): Move configuration finalization out of Main
  keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
Labels: ready to merge

#1009 fix(retrofit): Call propagate to get request ID, set user origin
  keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/AuthorizationHeadersInterceptor.kt
Labels: auto merged, ready to merge

#1022 chore(veto): move veto apis to application controller
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentArtifactPin.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
Labels: ready to merge

#1026 chore(dependencies): Use latest Kotlins
  build.gradle.kts
Labels: ready to merge

#1028 fix(deps): bump okhttp
  build.gradle.kts
Labels: ready to merge

#1025 chore(usability): Use consistent formats for task user
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
Labels: ready to merge

#1027 fix(errors): Replicate Spring's default error format for API errors
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt
Labels: auto merged, ready to merge

#1029 Send image diff to orca as bake task description
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/diff/DebugVisitor.kt
Labels: ready to merge

#1030 don't trigger region mismatch if there are more regions than we need
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
Labels: ready to merge

#1031 send image diff as a parameter rather than task description
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/actuation/TaskLauncher.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/model/OrchestrationRequest.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskLauncher.kt
Labels: ready to merge

#1012 fix(resourceEvent): emit ResourceDeltaResolved when actually needed
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
Labels: auto merged, ready to merge

#1034 default delivery config name
  gradle.properties
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/SubmittedDeliveryConfig.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
  keel-web/src/test/resources/examples/delivery-config-example.yml
Labels: ready to merge

#1037 fix test that leaks data
  gradle.properties
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/LegacySpecUpgradeTests.kt
Labels: ready to merge

#1038 fix(errors): Improve authorization error messages further
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt
Labels: ready to merge

#1039 fix(build): Add missing kork-exceptions version
  keel-api/keel-api.gradle.kts
Labels: ready to merge

#1032 chore(core): back out debug logging and single thread context
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
Labels: ready to merge

#1041 fix(export): Fix launch config export
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
Labels: ready to merge

#1047 remove old bakery/image@v1 example
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
  keel-web/src/test/resources/examples/image-example.yml
Labels: auto merged, ready to merge

#1056 fix(clouddriver): hasAppVersion edge case
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt
  keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImageTests.kt
Labels: ready to merge

#1054 ensure DeliveryArtifact schema is output correctly even if things render in a different order
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/SealedClassModelConverter.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
Labels: ready to merge

#1050 feat(configs): fetch config by app
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
Labels: ready to merge

#1062 fix(performance): Avoid retrieving all SGs when looking for one
  README.md
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
  keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
Labels: ready to merge

#1059 fix(artifacts): log instead of throw when artifacts have weird statuses
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
Labels: ready to merge

#1064 chore(telemetry): report drift time in seconds
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
Labels: ready to merge

#1055 feat(export): Export deployment strategy
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ClusterDeployStrategy.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelper.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
  keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelperTests.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/config/TitusConfig.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
  keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt
  keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
Labels: API, export

#1066 fix(security): Fix regression in adding X-SPINNAKER-ACCOUNTS
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
  keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/AuthorizationHeadersInterceptor.kt
  keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/KeelRetrofitConfiguration.kt
  keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/SpinnakerHeadersInterceptor.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt
Labels: ready to merge

#1065 fix(titus): filtering out non matching tags
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
Labels: ready to merge

#1040 Vetos for ensuring dependent security groups / load balancers exist
  keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/AmazonLoadBalancer.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ApplicationLoadBalancerModel.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClassicLoadBalancerModel.kt
  keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverServiceTests.kt
  keel-clouddriver/src/test/resources/loadBalancers.json
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/Veto.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/VetoEnforcer.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/DummyVeto.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/VetoEnforcerTests.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterDependencyContainer.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVeto.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVeto.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVetoTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVetoTests.kt
Labels: ready to merge

#1074 Revert "fix(performance): Avoid retrieving all SGs when looking for o…
  README.md
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
  keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
Labels: ready to merge

#1076 CloudDriver doesn't consistently return region, removed it from model
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/AmazonLoadBalancer.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ApplicationLoadBalancerModel.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClassicLoadBalancerModel.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVeto.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVetoTests.kt
Labels: ready to merge

#1077 fix(events): Add missing event sub-type
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
Labels: ready to merge

#1079 Disambiguate 404s
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
  keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
  keel-ec2-plugin/keel-ec2-plugin.gradle.kts
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVetoTests.kt
  keel-retrofit-test-support/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/errors.kt
Labels: ready to merge

#1070 feat(getAllApps): Endpoint to get all managed applications
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ApplicationSummary.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/AdminService.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AdminControllerTests.kt
Labels: ready to merge
