Repository spinnaker/keel, pull requests merged in 2020-01, with the labels that each got.

#699 removed function now in library
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/jsonschema/JsonSchemaGeneratorTests.kt
Labels: ready to merge

#705 default the value for promotion status
  keel-sql/src/main/resources/db/changelog/20191218-add-status-to-environment-artifact-versions.yml
  keel-sql/src/main/resources/db/changelog/20200107-default-promotion-status.yml
  keel-sql/src/main/resources/db/databaseChangeLog.yml
Labels: ready to merge

#695 refactor(export): Refactor export to simplify omitting defaults and creating overrides
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/diff/ResourceDiff.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceSpecExportHelper.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusImageResolver.kt
  keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
Labels: export, ready to merge

#704 feat(deliveryConfig): require delivery config, tie artifact to it
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt
  keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
  keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
  keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
  keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt
  keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/UnsupportedArtifactTypeException.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
  keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/ContainerProvider.kt
  keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/ContainerProviderDeserializer.kt
  keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/DockerImageResolver.kt
  keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/SampleDockerImageResolver.kt
  keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/SampleDockerImageResolverTests.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ImageProvider.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/ImageProviderDeserializer.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TaskLauncherTests.kt
  keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/TaskLauncher.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/ArtifactUtils.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
  keel-sql/src/main/resources/db/changelog/20200106-tie-artifacts-to-delivery-configs.yml
  keel-sql/src/main/resources/db/changelog/20200108-update-delivery-artifact-indicies.yml
  keel-sql/src/main/resources/db/databaseChangeLog.yml
  keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/DeliveryConfigs.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusImageResolver.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusServerGroup.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/exceptions/ErrorResolvingContainerException.kt
  keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt
Labels: auto merged, ready to merge

#708 fix(artifact): fixing uniqueness
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
  keel-sql/src/main/resources/db/changelog/20200109-fix-delivery-artifact-uniqueness.yml
  keel-sql/src/main/resources/db/databaseChangeLog.yml
Labels: ready to merge

#713 feat(constraint): configurable kayenta defaults
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Constraint.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintConfigurationProperties.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluator.kt
Labels: ready to merge

#716 bring actuationInProgress method signature in line
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
  keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
  keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
Labels: ready to merge

#724 chore(deb): add debug logs
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
  keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
Labels: ready to merge

#717 fix(artifacts): don't approve a version with an invalid status
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
  keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/NoImageFound.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
Labels: auto merged, ready to merge

#694 feat(*): Enable caching for Github Actions
  .github/workflows/pr.yml
Labels: auto merged, ready to merge

#732 chore(constraints): refactor updateConstraintStatus rest controller
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ConstraintState.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
Labels: ready to merge

#731 feat(deliveryConfig): delete and update configs
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt
  keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CleanerTests.kt
  keel-core/keel-core.gradle.kts
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/Cleaner.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryCleanerTests.kt
  keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/DockerImageResolver.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlCleanerTests.kt
  keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AdminControllerTests.kt
Labels: ready to merge

#734 feat(ec2): flexible region staggering for clusters
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ClusterDeployStrategy.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Constraint.kt
  keel-core/src/test/kotlin/com/netflix/spinnaker/keel/api/ClusterDeployStrategyTests.kt
  keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
  keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
  keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaExecutionUtils.kt
Labels: ready to merge

#759 make schema generator handle objects
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/jsonschema/JsonSchemaGenerator.kt
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/SchemaController.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/jsonschema/JsonSchemaGeneratorTests.kt
  keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/SchemaControllerTests.kt
Labels: ready to merge

#766 feat(environments): ability to pin artifact versions to environments
  keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
  keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
  keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/EnvironmentArtifactPin.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
  keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
  keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
  keel-sql/src/main/resources/db/changelog/20200127-environment-artifact-pin-table.yml
  keel-sql/src/main/resources/db/databaseChangeLog.yml
  keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
Labels: auto merged, ready to merge
